### ISSUE TITLE
Make package available on MELPA stable

### ISSUE THREAD

**Issue by selmanj** [pd/yard-mode.el#6]
Given that the last commit was 8 months ago, is it possible to add HEAD (`78792f6a6fbff4f1bc955f494fdb11378e7f8095`) to [MELPA stable](http://stable.melpa.org/)?  It's pretty easy to do; all you need is to create a tag of a version like `v0.1` and it'll automatically be added.

Something like the below should work:

```
$ git tag v0.1 78792f6a6fbff4f1bc955f494fdb11378e7f8095
$ git push origin v0.1
```

**Comment by pd** [comment]
Sorry for the delay, overaggressive email filter swallowed this.

```
~/sauce/el/yard-mode.el (master) » g push origin v0.1
Total 0 (delta 0), reused 0 (delta 0)
To github.com:pd/yard-mode.el.git
 * [new tag]         v0.1 -> v0.1
```
